$(window).load(function() {
	// Animate loader off screen
	$(".se-pre-con").delay(2000).fadeOut("slow");;
	$("#overlayer").delay(2000).fadeOut("slow");;
  });


var counter = 0;
$(document).bind("mousewheel",function(event){
	if(event.originalEvent.wheelDelta >5){
		counter -= 1;
		console.log(counter);
		$(".outer_box").css({"transform":"perspective(1000px) rotateX("+counter+"deg)" ,"-webkit-transform":"perspective(1000px) rotateX("+counter+"deg)"})
	}else{
		counter += 1;
		console.log(counter);
		$(".outer_box").css({"transform":"perspective(1000px) rotateX("+counter+"deg)","-webkit-transform":"perspective(1000px) rotateX("+counter+"deg)"})
	}
})

var counter = 0;
$(document).bind("mousewheel",function(event){
	if(event.originalEvent.wheelDelta >0){
		counter -= 10;
		console.log(counter);
		$(".outer_box1").css({"transform":"perspective(1000px) rotateX("+counter+"deg)","-webkit-transform":"perspective(1000px) rotateX("+counter+"deg)"})
	}else{
		counter += 10;
		console.log(counter);
		$(".outer_box1").css({"transform":"perspective(1000px) rotateX("+counter+"deg)","-webkit-transform":"perspective(1000px) rotateX("+counter+"deg)"})
	}
})

const myFunction = () => {
    document.getElementById("first").style.display ='block';
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  
  const myFunction2 = () => {
    document.getElementById("second").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  
  const myFunction3 = () => {
  document.getElementById("third").style.display ='block'
  document.getElementById("first").style.display ='none'
  document.getElementById("second").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction4 = () => {
    document.getElementById("t4").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction5 = () => {
    document.getElementById("t5").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction6 = () => {
    document.getElementById("t6").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction7 = () => {
    document.getElementById("t7").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction8 = () => {
    document.getElementById("t8").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction9 = () => {
    document.getElementById("t9").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction10 = () => {
    document.getElementById("t10").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction11 = () => {
    document.getElementById("t11").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction12 = () => {
    document.getElementById("t12").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction13 = () => {
    document.getElementById("t13").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction14 = () => {
    document.getElementById("t14").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction15 = () => {
    document.getElementById("t15").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction16 = () => {
    document.getElementById("t16").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction17 = () => {
    document.getElementById("t17").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction18 = () => {
    document.getElementById("t18").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t19").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction19 = () => {
    document.getElementById("t19").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t20").style.display ='none'
  }
  const myFunction20 = () => {
    document.getElementById("t20").style.display ='block'
    document.getElementById("first").style.display ='none'
    document.getElementById("second").style.display ='none'
    document.getElementById("third").style.display ='none'
    document.getElementById("t4").style.display ='none'
    document.getElementById("t5").style.display ='none'
    document.getElementById("t6").style.display ='none'
    document.getElementById("t7").style.display ='none'
    document.getElementById("t8").style.display ='none'
    document.getElementById("t9").style.display ='none'
    document.getElementById("t10").style.display ='none'
    document.getElementById("t11").style.display ='none'
    document.getElementById("t12").style.display ='none'
    document.getElementById("t13").style.display ='none'
    document.getElementById("t14").style.display ='none'
    document.getElementById("t15").style.display ='none'
    document.getElementById("t16").style.display ='none'
    document.getElementById("t17").style.display ='none'
    document.getElementById("t18").style.display ='none'
    document.getElementById("t19").style.display ='none'
  }
  
  